name = "ReferenceTests"
uuid = "324d217c-45ce-50fc-942e-d289b448e8cf"
authors = ["Christof Stocker <stocker.christof@gmail.com>", "Lyndon White <oxinabox@ucc.asn.au>"]
version = "0.6.1"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DeepDiffs = "ab62b9b5-e342-54a8-a765-a90f495de1a6"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ColorTypes = ">= 0.4"
FileIO = ">= 0.4"
ImageInTerminal = ">= 0.3"
Images = ">= 0.15"
julia = ">= 1.0"

[extras]
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["CSVFiles", "DataFrames", "FixedPointNumbers", "ImageMagick", "TestImages"]
